### ISSUE TITLE
Search broken?

### ISSUE THREAD

**Issue by mjgpy3** [EventStore/eventstore.org#1]
Search doesn't seem to be working on the new domain

![docs-broken-on-new-domain](https://user-images.githubusercontent.com/1709849/30686295-d6b1c13a-9e85-11e7-9ce5-6f2343abbd5f.gif)

**Comment by pgermishuys** [comment]
@mjgpy3 the source should be working now.

**Comment by mjgpy3** [comment]
@pgermishuys thanks!
