### ISSUE TITLE
CreatedDate in projection state

### ISSUE THREAD

**Issue by tich92** [EventStore/eventstore.org#11]
Hello. How I can use CreatedDate of event in projections, its need to build projections by that date, but 
this property does not exists in event data like this: 
![image](https://user-images.githubusercontent.com/8046825/34049124-e47b6a9c-e1be-11e7-82ca-8dfe0ebbd6c8.png)
Projection source code:
![image](https://user-images.githubusercontent.com/8046825/34049165-0c19bb8a-e1bf-11e7-9cdd-e46d9a2a06a8.png)

**Comment by jimmy-grande** [comment]
HI there, any update about this issue?

**Comment by ChrisChinchilla** [comment]
Hey @jimmy-grande you're probably better posting this in the code repo, this is the repo for the website and the core devs don't really pay much attention to it.

https://github.com/EventStore/EventStore

**Comment by jimmy-grande** [comment]
Ok, thank you. I think we should close this issue then.
