### ISSUE TITLE
Documentation page is loading toc.html recursively

### ISSUE THREAD

**Issue by Timbus** [EventStore/eventstore.org#29]
Having a hard time reading the documentation because my CPU fan won't stop spinning =/
Looks like you're loading toc.html over and over again in some kinda loop. Docfx bug?

It is happening in both firefox 60, and chrome 67 on Mac.

Here's the stack trace from chrome, for what it's worth:
```
...
--load (async)--
send (docfx.vendor.js:formatted:3796)
ajax (docfx.vendor.js:formatted:3578)
n.(anonymous function) (docfx.vendor.js:formatted:3630)
loadNavbar (docfx.js:360)
renderNavbar (docfx.js:346)
(anonymous) (docfx.js:398)
j (docfx.vendor.js:formatted:1308)
fireWith (docfx.vendor.js:formatted:1365)
x (docfx.vendor.js:formatted:3608)
(anonymous) (docfx.vendor.js:formatted:3790)
--load (async)--
{... repeat inf ...}
```

My 'network' tab just shows an insane number of calls to toc.html, as well.

Any ideas?

**Comment by ChrisChinchilla** [comment]
Thanks @Timbus I'll move this over to https://github.com/EventStore/docs.geteventstore.com/issues and take a look.
