### ISSUE TITLE
Confusing docs for Stream meta data

### ISSUE THREAD

**Issue by Ryan-Palmer** [EventStore/eventstore.org#66]
The copy [here](https://eventstore.org/docs/http-api/stream-metadata/index.html?tabs=tabid-1%2Ctabid-3%2Ctabid-5%2Ctabid-7) relating to stream metadata is a bit confusing, it seems to be mixed up advice describing stream and event meta, i.e.

> A common use case is to store information associated with an event that is not part of the event.
Examples of this are:
Which user wrote the event.

Surely this is only relevant to event meta?

Also the section on how to write to a stream's meta gives an example of an event you can send, $user-updated. There isn't an explanation of how this event works (for instance there is no user id to update the roles for?) and I can't find any definitive lists of events the the stream meta projection can handle.

> To update the metadata for a stream, issue a POST request to the metadata resource.

 

> Inside a file named metadata.json:

`[
    {
        "eventId": "7c314750-05e1-439f-b2eb-f5b0e019be72",
        "eventType": "$user-updated",
        "data": {
            "readRole": "$all",
            "metaReadRole": "$all"
        }
    }
]`

I did see there is an "update-acl" and "update-default-acl" stream meta event in the ACL docs. It is confusing that these are phrased as commands rather than events like $userUpdated, and that they don't have a dollar sign.

> The ACL below would give writer read and write permission on the stream, while reader would have read permission on the stream. Only users in the $admins group would be able to delete the stream or read and write the metadata.

> Inside a file named metadata.json:

`[
    {
        "eventId": "7c314750-05e1-439f-b2eb-f5b0e019be72",
        "eventType": "update-acl",
        "metadata": {
            "$acl": {
                "$w": "writer",
                "$r": [
                    "reader",
                    "also-reader"
                ],
                "$d": "$admins",
                "$mw": "$admins",
                "$mr": "$admins"
            }
        }
    }
]
`

Is it the case that there is a built in system projection that generates the stream's metadata state behind the scenes? It isn't configured by me in any way is it? So there must be specific events it looks for?

If I edit the ACL in the web UI I see a new event in the stream's meta called "$metadata" which presumably replaces the entire metadata state?

![image](https://user-images.githubusercontent.com/10651463/59286091-02529f00-8c67-11e9-9123-7dcb2ffbbc6a.png)

Essentially, I just find it all a bit confusing, it would be nice to have a clear explanation of how stream metadata works for a newbie, distinct from event meta. Currently the two are mixed and the information patchy and incomplete.

Oh and a tiny thing - the first line has strange grammar

> By default streams you create in Event Store have no metadata associated with it. 

I guess either 'a stream' or 'associated with them'

>

**Comment by gregoryyoung** [comment]
I can see where the confusion comes in. This will be pushed up to get a look at.

So obviously event metadata can be written per event. Stream metadata is associated with the stream. Some examples of things in a stream metadata would be $tb (truncate before) and $acl as in your example. There control the stream not individual events.

Stream metadata as can be seen in the screen capture ^^^ is implemented as a stream itself $${streamname} EG: its a known stream relationship. There are helper methods in the client API for interacting with stream metadata as opposed to just dealing with json. These methods would also be added to/updated if these were to change.

See the StreamMetadata class, some tests are using it https://github.com/EventStore/EventStore/blob/7f83df23e5ce388990ff304ed44052ffe7c56037/src/EventStore.Core.Tests/ClientAPI/when_working_with_stream_metadata_as_structured_info.cs. Basically though its just a little helper class giving easier access.




and I can see what you mean in the docs, there seem to be a few paragraphs in the stream metadata which appear to be a c/p etc from event metadata

"A common use of this information is to store associated details about an event that is not part of the event. Examples of these are:

"which user wrote the event?"
"Which application server were they talking to?"
"From what IP address did the request come from?"
This information is not part of the actual event but is metadata associated with the event. Event Store stores stream metadata as JSON, and you can access it over the HTTP APIs."

Cheers,

Greg

**Comment by RyanBuzzInteractive** [comment]
Thanks Greg, wasn't sure if I was losing the plot there for a moment!

I can see the helper methods for building stream meta in the client API tests you linked to, thanks.

I am using the http API however as I am connecting via a mobile client and there will be a lot of subscribers and I read that was the best approach.

Is there any docs on the meta data event types for http access? (i.e. the $user-updated, update-acl, $metadata above plus I guess others as well? ) It would be good to have a list of them and the data structures they require etc

**Comment by gregoryyoung** [comment]
Ah! For http there is also the http api https://eventstore.org/docs/http-api/stream-metadata/index.html?tabs=tabid-1%2Ctabid-3%2Ctabid-5%2Ctabid-7

The helper methods are just building the *json* that will be sent. This can help you whether using client API or not.

IIRC there is a rel link available to the metadata when reading the stream. You could also hardcode this (you will notice that they all follow the same format) however it is better to get it from the stream. I know its two http requests but in the future for some unknown reason we may end up changing the URI. If read from the stream as described your code will still work (we will provide the correct uri) where as if hardcoded it ....

**Comment by RyanBuzzInteractive** [comment]
Sorry if I am being thick or not explaining myself properly here!

I have read the http docs extensively, and quoted them in my original question.

They suggest posting specific events which update the meta, rather than replacing it with an entirely new blob of json, with event types such as $user-updated and update-acl.

There is no list of these event types or the body they require.

The given example is confusing as how can it update a user's role without their ID?

`[ { "eventId": "7c314750-05e1-439f-b2eb-f5b0e019be72", "eventType": "$user-updated", "data": { "readRole": "$all", "metaReadRole": "$all" } } ]`

**Comment by gregoryyoung** [comment]
They suggest posting specific events which update the meta, rather than replacing it with an entirely new blob of json, with event types such as $user-updated and update-acl.

These are internal events and get created when those actions happen.

**Comment by RyanBuzzInteractive** [comment]
Ok, but the ACL docs tell you to post those events to manage access?

![image](https://user-images.githubusercontent.com/10651463/59292608-519fcc00-8c75-11e9-89b0-857fa6bb7dd5.png)

**Comment by RyanBuzzInteractive** [comment]
Also the "Writing Metadata" link you posted literally tells you to post exactly that blob, why would it say that if they were internal? :

![image](https://user-images.githubusercontent.com/10651463/59292787-a6434700-8c75-11e9-99d3-4b8be467d578.png)

**Comment by gregoryyoung** [comment]
The helper class mentioned represents the *data* to post :) It has a builder + a ToJSON method https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/StreamMetadataBuilder.cs

It will give you what you need to post :)

**Comment by RyanBuzzInteractive** [comment]
Sorry, am I being totally stupid?

You are suggesting to build new meta data, built using the source / tests as a guide, then wholesale replacing the meta data, yes?

The docs do not describe that do they?

They _do_ describe an event-by-event transformation don't they? (as in my screenshots above)

Maybe we cross posted?

**Comment by gregoryyoung** [comment]
I agree the docs look suspect here. The link ^^^ will give you the exact json you need to post (has helper methods for setting them). As far as I know its a wholesale *replacement* of the metadata.

I am also a bit confused by some of the things shown in the docs.

**Comment by RyanBuzzInteractive** [comment]
Ok cool thanks, I will treat meta data updates as complete replacements with each call, not delta updates, and I guess I use the $metadata event type?

Presumable then all remote ACL management has to be done with complete meta data replacements, not  update deltas?

Does that mean the ability to write meta data and the ability to manage ACLs is one and the same thing?

**Comment by gregoryyoung** [comment]
"Does that mean the ability to write meta data and the ability to manage ACLs is one and the same thing?"

Yes ... Obviously there is also the adding the ACL to users etc (its just one side of it). But yes the interaction control is all in the stream metadata, stream metadata is separate from streamwrite however!

I have to look to give a proper answer but IIRC there is also a default that can be used which would be set on the $settings stream (I think its covered in the doc ^^^). Basically you are setting a default ACL to be used if no ACL exists. Given that the *vast* majority of the time the ACL is the same for > 90% of streams this is what ends up being done then overriden when needed.

There have been discussions at varying points of also adding some kind of "group" mechanism here (either implicit or explicit implicit being say a pattern match on stream name). I would be interested in hearing your thoughts on it. One method discussed was just stating "stream3 belongs to ACL group cheeseburgers" then the ACL can be set on "cheeseburgers". Another this ACL applies to cheeseburger-* :)

**Comment by RyanBuzzInteractive** [comment]
I am in exactly this kind of position actually, I am trying to create a team data collection app, with some users being team leaders who will invite others into the group. They will all then share data. 

It will use a website to manage the teams but they will be collecting data in the field using mobile devices, offline, then syncing when back online.

I have taken my lead from your talk on the police report thing, but I have a million questions I am trying to work through in my head. I'm an experienced mobile dev but little server experience and brand new to Event Store / event sourcing / cqrs so it is a challenge to say the least.

I have a couple of Google Group posts going on it if you have the time to chip in, I would super appreciate it! https://groups.google.com/forum/#!topic/event-store/Ha844lXp_6k

**Comment by ChrisChinchilla** [comment]
Closing this issue now. Some of the wording has been updated, but a lot of the issues here stem from something we need to clarify better (issues created) but isn't directly connected to this issue. That is that everything in Event Store is an event, and it's not that these examples show the event you *should* send, rather an event you *could* send.
