### ISSUE TITLE
Add blog author to template

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/eventstore.org#72]
The template for blogs is currently missing the author, we should add it.

**Comment by danjamescrosby** [comment]
Author section now added to blog posts template - holding off adding it to the blog home template as that is being redesigned.

By default, the author defined in a post's front matter is shown at the top. If the author is defined in _config.yml (an example has been added) it will show an author bio at the bottom of the post. 

The layout of both post and archive templates will be readdressed in the upcoming website review project.
